title: Gazeta Universitária
description: > # this means to ignore newlines until "baseurl:"
  Do Centro Universitário Integrado, o jornal online "Gazeta Universitária": a fim de informar e colocar em debate questões pertinentes ao mundo acadêmico, em especial, 
  nessa edição, o contexto de adaptação e vínculo estudantil.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "gazetauniversitaria.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author: Gazeta Universitária 
author-img: integrado.png 
about-author: | 
  De estudante para estudante. 
  Edição: Adaptação e vínculo na Universidade.
social-facebook: 
social-email: anakrichicovski@hotmail.com
social-github: gazetauniversitaria

discus-identifier: gazetauni 

# Tracker
analytics: # Google Analytics

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
